# Numerical computing in Julia

In [1]:
using LinearAlgebra

# Array, Vector and Matrix

Arrays are containers that store information contiguously in memory

In [2]:
# Vectors are 1-dimensional arrays
Vector

Array{T,1} where T

In [3]:
# Matrices are 2-dimensional arrays
Matrix

Array{T,2} where T

In [4]:
M = [
    [11.0 12.0];
    [21.0 22.0]
]
# Matrices are stored in Column-Major
M[:]  # display elements of M as ordered in the memory

4-element Array{Float64,1}:
 11.0
 21.0
 12.0
 22.0

# Linear Algebra

Official documentation: https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/

Julia provides native implementations of many (if not all) common linear algebra operations:
* vector-vector, matrix-vector, matrix-matrix operations
* trace, determinant, eigenvalue decomposition...
* matrix factorization: LU, QR, Cholesky, LDL'

Specialized implementations are provided for certain classes of matrices, e.g.:
* Dense vs Sparse linear algebra
* Diagonal, Tri-diagonal, Symmetric/Hermitian matrices

## Dense linear algebra

Linear algebra operations on dense matrices/vectors will result (when possible) in a BLAS call

In [5]:
A = [
    [1.0 2.0];
    [2.0 1.0]
]
x = [1.0, 1.0]

A*x  # That matrix-vector product is (ultimately) a call to BLAS gemv!

2-element Array{Float64,1}:
 3.0
 3.0

In [6]:
# It is possible to call BLAS routines directly
y = [0.0, 0.0]
BLAS.gemv!('N', 1.0, A, x, 0.0, y)

2-element Array{Float64,1}:
 3.0
 3.0

Dense matrix factorizations generally call functions from LAPACK.

Native implementations are also provided for general matrices.

In [7]:
lu(A)

LU{Float64,Array{Float64,2}}
L factor:
2×2 Array{Float64,2}:
 1.0  0.0
 0.5  1.0
U factor:
2×2 Array{Float64,2}:
 2.0  1.0
 0.0  1.5

## Sparse linear algebra

Documentation: https://docs.julialang.org/en/v1/stdlib/SparseArrays/

In [8]:
using SparseArrays

Sparse matrices are stored in Compressed Sparse Column (CSC) format

In [9]:
sA = sparse([
    [0.0 2.0];
    [2.0 0.0]
])

2×2 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [2, 1]  =  2.0
  [1, 2]  =  2.0

Common sparse linear algebra (e.g. matrix-vector products) use the default, native implementation.

In [10]:
x = ones(2)
sA * x

2-element Array{Float64,1}:
 2.0
 2.0

Sparse matrix factorization call functions from SuiteSparse

In [11]:
lu(sA)

UMFPACK LU Factorization of a (2, 2) sparse matrix
Ptr{Nothing} @0x000000000366eae0

In [12]:
@which lu(sA)

lu(S::SparseMatrixCSC{#s558,#s557} where #s557<:Union{Int32, Int64} where #s558<:Union{Complex{Float64}, Float64}) in SuiteSparse.UMFPACK at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SuiteSparse/src/umfpack.jl:152